### PR TITLE
MAINT: Updated installation instructions in README

### PR DESCRIPTION
**Pull request by VinzentRisch**
Solves issues #36 and #35

- Added apple silicon installation instructions.
- Removed altair from installation instructions.

To test this run the installation instructions in the README.md file

### CODE REVIEW

**Review by misialq — COMMENTED** [review]
Hey @VinzentRisch, this looks good! Maybe for the sake of completeness you could include Linux? I'm guessing it'll be the same as macOS Intel so you can just add it to the section title, but please do try if it works before 🙏

**Comment by VinzentRisch** [comment]
Yes that makes sense. How can i try on linux? Maybe on the euler server?

**Comment by misialq** [comment]
Yup, Euler should do!

**Comment by VinzentRisch** [comment]
Yes it works, I added Linux to the instruction title.

**Review by misialq — APPROVED** [review]
Awesome, merge away!

**Pull request merged**
