### PR TITLE
MAINT: Removed "overall-mapping-stats.txt" from `CARDGeneAnnotationDirectoryFormat`

### LINKED ISSUE #28: `CARDGeneAnnotationDirectoryFormat` contains stats file that is not needed
- The action `annotate-reads-card` produces artifacts of type `CARDAlleleAnnotation` and `CARDGeneAnnotation` containing the amr annotations but also mapping statistics per sample. This file, called "overall-mapping-stats.txt", is only needed in one artifact.

- To address this issue the `CARDGeneAnnotationDirectoryFormat` and the `annotate-reads-card` action have to be altered.

- Also the visualizer `visualize-annotation-stats` has to be altered to only accept inputs of CARDAlleleAnnotation

### PR DESCRIPTION
**Pull request by VinzentRisch**
This PR fixes #28 and #30 

- Removed "overall-mapping-stats.txt" from `CARDGeneAnnotationDirectoryFormat`.
- Changed the input of `visualize-annotation-stats` to only accept `CARDAlleleAnnotation` because the stats file is now only included in the `CARDAlleleAnnotationDirectoryFormat`.
- Changed `CARDAlleleAnnotation` to `SampleData[CARDAlleleAnnotation]` in the input plugin_setup of `visualize-annotation-stats`.
- Changed `annotate-reads-card` so that "overall-mapping-stats.txt" only gets moved to the `CARDAlleleAnnotation` artifact.

To test `annotate-reads-card` action, [download test files](https://polybox.ethz.ch/index.php/s/nJmbGpkM1ywS9VW) and run this (takes about 3 mins):

`qiime amr annotate-reads-card --i-reads 25mb_reads.qza --i-card-db card_db.qza --output-dir test_q2_amr_29 --p-threads 2`

To test `visualize-annotation-stats` run this:

`qiime amr visualize-annotation-stats --i-amr-reads-annotation test_q2_amr_29/amr_allele_annotation.qza --o-visualization test_q2_amr_29/amr_allele_annotation_stats.qzv`

### CODE REVIEW

**Comment by VinzentRisch** [comment]
Hi Santiago :) This is again a very small one with no new functionality.
I added the test data to download and the command to run. Everything should run quickly without any problems.

**Comment by Sann5** [comment]
Coolioou, I'll check it out :).

**Comment by Sann5** [comment]
In your second bullet point of the PR message you say
> Changed the input of visualize-annotation-stats to only accept CARDAlleleAnnotation because the stats file is now only included in the CARDGeneAnnotationDirectoryFormat.

Do you mean? 
> Changed the input of visualize-annotation-stats to only accept CARDAlleleAnnotation because the stats file is now only included in the CARD**Allele**AnnotationDirectoryFormat.

**Review by Sann5 — COMMENTED** [review]
- ✅ I all looks good to me! 
- ✅ All test pass locally.
- ✅ `annotate-reads-card` and `visualize-annotation-stats` run without problems. I did not inspect the outputs to make sure that made sense (not that I could either), but I guess you did this :)
- ❓Im just curious about one thing. How come you decided to set `"amr_reads_annotation": SampleData[CARDAlleleAnnotation]` and not `"amr_reads_annotation": CARDAlleleAnnotation`. I'm not an expert on Semantic Types so It's not so obvious why one would choose one over the other. Also apparently you already had `CARDAlleleAnnotation` registered as a type of `SampleData` before this PR so I am confused why you didn't use it before.

**Comment by VinzentRisch** [comment]
Thank you! 👍 
Thanks for pointing that out, I did mean CARDAlleleAnnotationDirectoryFormat. :)

And it should have been SampleData[CARDAlleleAnnotation] from the start. That was a bug, `visualize-annotation-stats` did not work some time before this fix.
So you can't choose the one or the other.

**Pull request merged**
