### PR TITLE
ENH: Added `GeneLength` semantic type

### LINKED ISSUE #42: Adding `Genelengths` type
Like described in #23, several normalization methods will be added to the plugin.
The FPKM and TPM methods both need information about the gene lengths.
This information can be extracted from the artifacts with type `CARDAlleleAnnotation` and `CARDGeneAnnotation`.
To ensure that feature tables from other sources can be normalized with these methods, a new type called `Genelength` has to be introduced.
The type will include one TSV file with two columns: One with the gene names and one with the corresponding gene lengths.
Additionally a transformer has to be introduced that converts `CARDAlleleAnnotation` and `CARDGeneAnnotation` to `Genelength`.

### PR DESCRIPTION
**Pull request by VinzentRisch**
This PR was created to fix #42. 

- Added `GeneLength` type
- Added `GeneLengthFormat` and `GeneLengthDirectoryFormat`
- Added transformer from `CARDAlleleAnnotationDirectoryFormat`/`CARDGeneAnnotationDirectoryFormat` -> `GeneLengthDirectoryFormat`
- Like described in #42, this type is needed for TPM and FPKM normalization methods, that will be implemented later (#23).

### Set up an environment
```bash
CONDA_SUBDIR=osx-64 mamba create -yn q2-amr \
  -c conda-forge -c bioconda -c qiime2 -c defaults \
  -c https://packages.qiime2.org/qiime2/2023.9/shotgun/released/ \
  qiime2 q2cli q2templates q2-types q2-types-genomics rgi

conda activate q2-amr
conda config --env --set subdir osx-64

pip install --no-deps --force-reinstall \
  git+https://github.com/misialq/rgi.git@py38-fix \
```

### Run it locally 
1. First, clone the repo and checkout the PR branch:
```bash
git clone https://github.com/bokulich-lab/q2-amr.git
cd q2-amr
git fetch origin pull/43/head:pr-43
git checkout pr-43
pip install -e .
```
2. [Download test file](https://polybox.ethz.ch/index.php/s/nJmbGpkM1ywS9VW): gene_length.txt

3. Test it out!
```bash
qiime tools import --input-path gene_length.txt --output-path gene_length.qza --type GeneLength
```

### CODE REVIEW

**Comment by VinzentRisch** [comment]
Hi @misialq 
Is the handling with the transformer correct like this? 
So that my normalize function would take a `GeneLengthDirectoryFormat` as input.
Because I also saw that if i want to give a FeatureTable as an input somewhere i give directly the biom.Table. So maybe it would make more sense to write a transformer that converts to pd.Series directly, because this would be needed in the end by the normalize function.

**Comment by VinzentRisch** [comment]
Hi @Sann5 :) 
Could you review this PR for me?
It's a small one with just an added Semantic type.

**Comment by Sann5** [comment]
Hey @VinzentRisch. I'll take a look! How urgent is this? Cus I have an important task that Michal left me atm. If its not urgent I would review this only after I'm finished with that.

**Comment by VinzentRisch** [comment]
No worries :) 
I'll ask @ChristosMatzoros to do it.

**Pull request closed without merging**
