### PR TITLE
MAINT: Changed the function `load_card_db` to load all files globally instead of locally.

### PR DESCRIPTION
**Pull request by VinzentRisch**
solves #65 

- Removed the --local flag in the load function and the annotation functions.

### Set up an environment for apple silicone
```bash
CONDA_SUBDIR=osx-64 mamba create -yn q2-amr \
  -c conda-forge -c bioconda -c qiime2 -c defaults \
  -c https://packages.qiime2.org/qiime2/2024.2/shotgun/released/ \
  qiime2 q2cli q2templates q2-types rgi

conda activate q2-amr
conda config --env --set subdir osx-64

pip install --no-deps --force-reinstall \
  git+https://github.com/misialq/rgi.git@py38-fix \

pip install git+https://github.com/qiime2/qiime2.git  
```

### Run it locally 
1. First, clone the repo and checkout the PR branch:
```bash
git clone https://github.com/bokulich-lab/q2-amr.git
cd q2-amr
git fetch origin pull/66/head:pr-66
git checkout pr-66
pip install -e .
```
solves #51 

- Three transformers have been added from the formats `CARDMAGsKmerAnalysisDirectoryFormat`, `CARDReadsAlleleKmerAnalysisDirectoryFormat` and `CARDReadsGeneKmerAnalysisDirectoryFormat` to `qiime2.Metadata`. This enables the user to use these formats with the function `metadata tabulate` to explore the analysis output in a browser.
- The function `tabulate_data` has been expanded. in this process also a bug has been fixed for the tabulation of the MAGs tables.

### Set up an environment for apple silicone
```bash
CONDA_SUBDIR=osx-64 mamba create -yn q2-amr \
  -c conda-forge -c bioconda -c qiime2 -c defaults \
  -c https://packages.qiime2.org/qiime2/2024.2/shotgun/released/ \
  qiime2 q2cli q2templates q2-types rgi

conda activate q2-amr
conda config --env --set subdir osx-64

pip install --no-deps --force-reinstall \
  git+https://github.com/misialq/rgi.git@py38-fix \

pip install git+https://github.com/qiime2/qiime2.git  
```

### Run it locally 
1. First, clone the repo and checkout the PR branch:
```bash
git clone https://github.com/bokulich-lab/q2-amr.git
cd q2-amr
git fetch origin pull/71/head:pr-71
git checkout pr-71
pip install -e .
```
2. Download test files 
[download reads.qza, mags.qza and card_db.qza](https://polybox.ethz.ch/index.php/s/nJmbGpkM1ywS9VW): 

3. Test it out!

Run all commands 
```bash
qiime amr annotate-reads-card --i-reads reads.qza --i-card-db card_db.qza --p-threads 10 --output-dir reads_amr_annotation
qiime amr annotate-mags-card --i-mag mags.qza --i-card-db card_db.qza --p-threads 10 --output-dir mags_amr_annotation

 ```

### CODE REVIEW

**Review by misialq — COMMENTED** [review]
Just a question, as I don't remember how this DB loading worked exactly: where do the DB files get stored when either of those options is toggled?

**Comment by ChristosMatzoros** [comment]
Hey @VinzentRisch,

Can you add here a link to the documentation regarding the `--local` parameter? 

Thanks

**Review by misialq — APPROVED** [review]
Hey @VinzentRisch, thanks for the explanation! This is a conditional ✅: could you please test that it works also with parallelization? If yes, feel free to go ahead and merge 🚀

**Review by ChristosMatzoros — APPROVED** [review]
Hey @VinzentRisch, 
Everything has been tested on my side and is working perfectly! Feel free to merge after you address the request from @misialq. :rocket:

**Comment by misialq** [comment]
Hey @VinzentRisch, what's up with this PR?

**Comment by VinzentRisch** [comment]
This works in testing also with parsl parallelisation.
With reads annotation and also with kmer analysis.

**Comment by VinzentRisch** [comment]
Hey @misialq can you please merge this for me? Thanks!

**Pull request merged**
