### PR TITLE
BUG: Fixed bug in  sample_dict of `CARDAnnotationDirectoryFormat`

### PR DESCRIPTION
**Pull request by VinzentRisch**
solves #72 

### Set up an environment for apple intel
```bash
mamba create -yn q2-amr \
  -c https://packages.qiime2.org/qiime2/2024.2/shotgun/released/  \
  -c qiime2 -c conda-forge -c bioconda -c defaults \
  qiime2 q2cli q2templates q2-types rgi

conda activate q2-amr

pip install --no-deps --force-reinstall \
  git+https://github.com/misialq/rgi.git@py38-fix \

pip install git+https://github.com/qiime2/qiime2.git  
```

### Run it locally 
1. First, clone the repo and checkout the PR branch:
```bash
git clone https://github.com/bokulich-lab/q2-amr.git
cd q2-amr
git fetch origin pull/73/head:pr-73
git checkout pr-73
pip install -e .

### CODE REVIEW

**Comment by VinzentRisch** [comment]
Hi @misialq 
Can you look this over?
With this change the partition action now works correctly and is much easier.

**Review by misialq — CHANGES_REQUESTED** [review]
Hey @VinzentRisch, I do not think that this should be the right solution to the issue you linked. Your MAGs get overwritten because _you_ are overwriting them in-place in the for-loop (how did we miss this in the previous review... 🤦 ). You should instead `update` the dictionary to keep _adding_ the MAGs rather then replacing those. Also, you should change the tests to add a case where this would be detected.

**Comment by VinzentRisch** [comment]
Hey @misialq, yes I know what the problem is with the overwriting. Here I changed the structure to not be a nested dictionary because this approach is much easier to work with in the partition actions #54. I dont think it makes sense that sample_dict returns a nested dict because I cant see any advantage of that approach. 
But I should have created a new issue, this PR now does not really fit to the linked issue anymore.
Can you have a look at #54, there I already implemented the changes from this PR and this change makes the code much more readable.

**Comment by misialq** [comment]
Well, let me list some reasons/thoughts as to why it would be beneficial to do it this way:
- in short, this is the most intuitive way to represent the hierarchical nature of the directories you are trying to get the paths for
- in your case, the keys of the dictionary would just become very "strange", frankensteinian strings which would be a mixture of less-random sample names and completely random UUIDs with dashes in them separated by a slash - good luck to anyone who has to debug this ever in the future 
- when looking at this nested dict it is immediately obvious what is represented by which level - it's not really more difficult to work with it, it just requires a slight code rewrite
- the method is called `sample_dict` which implies it will return information about "samples" - not some arbitrary combination of strings which happen to be "sample/mag" in this case
- if anyone ever needs to collect a list of sample IDs or mag IDs they will just need to call the `keys` method on your dictionary (or the nested dictionaries) without worrying about _anything_ else - this is one of the _main_ reasons for introducing this method in the first place
- this representation will allow splitting your datasets based on sample _or_ mag _or_ both if ever required - it wouldn't be possible if you do it in your "simplified" way

I did check out your other PR and I don't see how it would be more difficult to use the `sample_dict` I had originally proposed. In fact, if you had implemented the partitioning in a fashion similar to how we did it in other places you would end up with the same amount of code, if not less. Please check out my comments on the PR you linked to see what I mean. Please do let me know, though, in case I missed something which is specific to the CARD directory formats - we can discuss more.

**Comment by VinzentRisch** [comment]
Yes those are very valid points :) 
My keys with a slash definitely feel hacky. 
I looked at the comments on #54 and I know about your implementation in the moshpit function and my first attempt was similar. The difference between the structure of SampleData[MAgs] and SampleData[CardAnnotation] is that there are multiple files per MAG in SampleData[CardAnnotation] and when using the array split function it splits the files that belong to one MAG into different partitions, but I just have to adjust the list to have one entry per MAG with two paths.

**Review by misialq — APPROVED** [review]
Hey @VinzentRisch, that looks perfect, thanks! 🙏 One comment before merging: could you please first update #75, merge it and then update this PR with those changes so that we can see the tests pass? Thanks!

**Pull request merged**
