### PR TITLE
ENH: Adding `AMRFinderPlusAnnotation` type

### PR DESCRIPTION
**Pull request by VinzentRisch**
solves #85

- Added new type `SampleData[AMRFinderPlusAnnotations]` to be used with SampleData[MAGs] annotation.
- Added new type `FeatureData[AMRFinderPlusAnnotation]` to be used with FeatureData[Sequence] annotation.

### Set up an environment 
```
CONDA_SUBDIR=osx-64 mamba create -yn q2-amr \
  -c https://packages.qiime2.org/qiime2/2024.2/shotgun/released/ \
  -c qiime2 -c conda-forge -c bioconda -c defaults \
  qiime2 q2cli q2templates q2-types rgi tqdm jellyfish ncbi-amrfinderplus

conda activate q2-amr
conda config --env --set subdir osx-64

pip install --no-deps --force-reinstall \
  git+https://github.com/misialq/rgi.git@py38-fix \
  git+https://github.com/bokulich-lab/q2-amr.git
```

### Run it locally 
1. First, clone the repo and checkout the PR branch:
```bash
git clone https://github.com/bokulich-lab/q2-amr.git
cd q2-amr
git fetch origin pull/86/head:pr-86
git checkout pr-86
pip install -e .
```
Download test data: 
[PR-86.zip](https://github.com/user-attachments/files/16179238/PR-86.zip)

2. Test it out!
```bash
qiime tools import --input-path sample_data --output-path amr_annotations.qza --type "SampleData[AMRFinderPlusAnnotations]"
qiime tools import --input-path feature_data --output-path amr_annotation.qza --type "FeatureData[AMRFinderPlusAnnotation]"
```

### CODE REVIEW

**Review by ChristosMatzoros — APPROVED** [review]
The code looks great and everything works as expected!!

**Comment by VinzentRisch** [comment]
Hi @misialq 
Can you merge this one for me too? 
And can you remove those checks that are not needed anymore so i can merge the PRs by myself? The checks are still there also on newly created PRs.

**Comment by misialq** [comment]
Hey @VinzentRisch, I finally figured why all these check were always appearing on all of your PRs and fixed it - from now on, only the two should be visible. What I am wondering, though, is why the coverage report does not show up here (or anywhere else?) - can you please investigate? I'm merging this one in the meantime.

**Comment by misialq** [comment]
Oh, and let's stop using the `` ticks in commit names/PR titles - it breaks our CI 😅

**Comment by VinzentRisch** [comment]
On the topic of CI bugs. @misialq 
I think revert commits also break the CI
see here: https://github.com/bokulich-lab/q2-amr/actions/runs/9807765273/job/27082173410?pr=86#step:4:12
Or is it something else?

**Comment by misialq** [comment]
Yeah, it seems so... my suspicion is that the additional quotation marks `"` in the revert commit message may have something to do with that...

**Pull request merged**
