### PR TITLE
BUG: Changed `read_in_txt` helper function to use unique column as index for allele mapping data

### LINKED ISSUE #26: BUG: "biom.exception.TableException: Duplicate observation IDs" when running `annotate-reads-card`
The error message **biom.exception.TableException: Duplicate observation IDs** occurs when running the action `annotate-reads-card` with the flag `--p-include-wildcard`.

The error occurs during the creation of the feature table, when the `pd.Dataframe` gets converted into a biom file.
The biom format does not allow duplicated ID values.
The helper function `create_count_table` uses the column _ARO_Term_ in the file allele_mapping_data.txt. When using `annotate-reads-card` without the flag `--p-include-wildcard`, this does not lead to any issues. But with the flag, a secondary database with multiple alleles per gene is introduced, which can lead to duplications in the _ARO_Term_ column.

To solve this issue a secondary unique identifier has to be added to the _ARO_Term_ column  to ensure there are no duplicates in the index of the biom file.

### PR DESCRIPTION
**Pull request by VinzentRisch**
This PR was created to fix #26. 

- Added new map_type parameter to `read_in_txt`.
- If `map_type` is set to "allele" the column _Reference Sequence_ is used as the index for the count tables. _Reference Sequence_ values are unique and this solves the issue with the biom table format. Only downside is that the unique identifiers are quite long and not very readable (eg. Prevalence_Sequence_ID:97743|ID:1437|Name:AcrF|ARO:3000502) instead of just AcrF
- If `map_type` is set to "gene" the behaviour is as before and the column _ARO Term_ is used as the index.

### Set up an environment
```bash
CONDA_SUBDIR=osx-64 mamba create -yn q2-amr \
  -c conda-forge -c bioconda -c qiime2 -c defaults \
  -c https://packages.qiime2.org/qiime2/2023.9/shotgun/released/ \
  qiime2 q2cli q2templates q2-types q2-types-genomics rgi

conda activate q2-amr
conda config --env --set subdir osx-64

pip install --no-deps --force-reinstall \
  git+https://github.com/misialq/rgi.git@py38-fix \
  git+https://github.com/bokulich-lab/q2-amr.git
```

### Run it locally 
1. First, clone the repo and checkout the PR branch:
```bash
git clone https://github.com/bokulich-lab/q2-amr.git
cd q2-amr
git fetch origin pull/27/head:pr-27
git checkout pr-27
pip install -e .
```
2. [Download test files](https://polybox.ethz.ch/index.php/s/nJmbGpkM1ywS9VW) reads.qza and card_db.qza

3. Test it out!
Takes about 10 min.
```bash
qiime amr annotate-reads-card --i-reads 25mb_reads.qza --i-card-db card_db.qza --output-dir test_27 --p-threads 2 --p-include-wildcard
```

### CODE REVIEW

**Comment by misialq** [comment]
Hey @ChristosMatzoros, could you please check this one out? Thanks!

**Review by ChristosMatzoros — APPROVED** [review]
Thank you for putting this together @VinzentRisch. I executed both the old and new code and achieved the expected results. You did an excellent job introducing the unique identifier for allele mappings, effectively preventing duplicate IDs in the biom table. I consider this to be the most straightforward and clean solution. Regarding the size of the unique identifiers, I believe they do not detract from readability; quite the opposite, they may provide important information to the user. Everything seems ok from my side!

**Review by ChristosMatzoros — APPROVED** [review]

**Comment by VinzentRisch** [comment]
Hi @misialq, @ChristosMatzoros just reviewed and approved my changes, but i still can't merge the PR.
I think it is because @ChristosMatzoros lacks the needed permissions to approve my changes.
Can you give @ChristosMatzoros these permissions?

**Comment by misialq** [comment]
Hey @VinzentRisch, sorry about that - I fixed the permissions and you should be able to merge now (after updating). 🚀

**Pull request merged**
